/// Data model for Note objects
///
/// This file defines the Notes class which represents a single note in the application
/// It includes serialization methods for Firebase Firestore integration

import 'package:cloud_firestore/cloud_firestore.dart';

/// Represents a single note in the application
///
/// This immutable data class contains all properties of a note including:
/// - Basic content (title, content, id)
/// - Timestamps (creation and update times)
/// - Organization features (color coding, pinning, tags)
class Notes{
  /// The title/heading of the note
  final String title;

  /// The main content/body of the note
  /// Supports markdown formatting when displayed
  final String content;

  /// Unique identifier for the note
  /// Generated by Firestore when creating a new note
  final String id;

  /// Timestamp when the note was originally created
  final DateTime createdAt;

  /// Timestamp when the note was last modified
  /// Updated whenever the note is edited or pinned/unpinned
  final DateTime updatedAt;

  /// Index representing the color theme of the note
  /// Used for visual organization (default: 0)
  final int colorIndex;

  /// Whether the note is pinned to the top of the list
  /// Pinned notes appear before unpinned notes regardless of update time
  final bool ispinned;

  /// List of tag strings for categorizing/organizing notes
  /// Tags can be searched and filtered
  final List<String> tags;

  /// Constructor for creating a Notes instance
  ///
  /// Required parameters:
  /// - [title]: The note's title
  /// - [content]: The note's content
  /// - [id]: Unique identifier
  /// - [createdAt]: Creation timestamp
  /// - [updatedAt]: Last modification timestamp
  ///
  /// Optional parameters with defaults:
  /// - [colorIndex]: Color theme index (default: 0)
  /// - [ispinned]: Pin status (default: false)
  /// - [tags]: List of tags (default: empty list)
  Notes(
    {
    required this.title,
    required this.content,
    required this.id,
    required this.createdAt,
    required this.updatedAt,
     this.colorIndex =  0,
     this.ispinned = false,
     this.tags= const [],
    });

  /// Converts the Notes object to a Map for Firestore storage
  ///
  /// DateTime objects are converted to Firestore Timestamps
  /// Returns a Map< String, dynamic> compatible with Firestore document structure
  Map<String, dynamic> toMap(){
    return {
      'title': title,
      'content': content,
      'id': id,
      // Convert DateTime to Firestore Timestamp for proper storage
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': Timestamp.fromDate(updatedAt),
      'colorIndex': colorIndex,
      'ispinned': ispinned,
      'tags': tags,
    };
  }

  /// Factory constructor to create a Notes object from a Firestore Map
  ///
  /// Deserializes data retrieved from Firestore into a Notes instance
  /// Provides default values for missing fields to prevent null errors
  ///
  /// Parameters:
  /// - [map]: The Map containing note data from Firestore
  ///
  /// Returns: A new Notes instance with the data from the map
  factory Notes.fromMap(Map<String, dynamic> map){
    return Notes(
      // Use null-coalescing operator to provide defaults for missing fields
      title: map['title'] ?? '',
      content: map['content'] ?? '',
      id: map['id'] ?? '',
      // Convert Firestore Timestamp back to DateTime
      createdAt: (map['createdAt'] as Timestamp).toDate(),
      updatedAt: (map['updatedAt'] as Timestamp).toDate(),
      colorIndex: map['colorIndex'] ?? 0,
      ispinned: map['ispinned'] ?? false,
      // Safely convert dynamic list to List<String>
      tags: List<String>.from(map['tags'] ?? []),
    );
  }

  /// Creates a copy of this Notes instance with modified fields
  ///
  /// This method implements the immutable data pattern
  /// All parameters are optional - only provided values will be changed
  ///
  /// Useful for updating notes without mutating the original object
  ///
  /// Parameters: All optional named parameters matching Notes fields
  /// Returns: A new Notes instance with updated values
  Notes copyWith({
    String? title,
    String? content,
    String? id,
    DateTime? createdAt,
    DateTime? updatedAt,
    int? colorIndex,
    bool? ispinned,
    List<String>? tags,
  })
  {
    return Notes(
      // Use provided value if not null, otherwise keep existing value
      title: title ?? this.title,
      content: content ?? this.content,
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      colorIndex: colorIndex ?? this.colorIndex,
      ispinned: ispinned ?? this.ispinned,
      tags: tags ?? this.tags,
    );
  }
}