// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2hIeX8x_bzAQ2XmJLKivkHxa2P7nZtZo',
    appId: '1:216614376186:web:9cd4dc23f591d843e16f43',
    messagingSenderId: '216614376186',
    projectId: 'note-app-19de7',
    authDomain: 'note-app-19de7.firebaseapp.com',
    storageBucket: 'note-app-19de7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL4lg0ZOqk_PVXUQi2A5BggKZprZjeBs8',
    appId: '1:216614376186:android:95b86e19483ebfd7e16f43',
    messagingSenderId: '216614376186',
    projectId: 'note-app-19de7',
    storageBucket: 'note-app-19de7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_XXHGVS7ra9VDvHrRNKfLxsVNGRGEuMY',
    appId: '1:216614376186:ios:703ad6a067e38d12e16f43',
    messagingSenderId: '216614376186',
    projectId: 'note-app-19de7',
    storageBucket: 'note-app-19de7.firebasestorage.app',
    iosBundleId: 'com.example.finalNoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_XXHGVS7ra9VDvHrRNKfLxsVNGRGEuMY',
    appId: '1:216614376186:ios:703ad6a067e38d12e16f43',
    messagingSenderId: '216614376186',
    projectId: 'note-app-19de7',
    storageBucket: 'note-app-19de7.firebasestorage.app',
    iosBundleId: 'com.example.finalNoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2hIeX8x_bzAQ2XmJLKivkHxa2P7nZtZo',
    appId: '1:216614376186:web:f9bc635e8b194eb2e16f43',
    messagingSenderId: '216614376186',
    projectId: 'note-app-19de7',
    authDomain: 'note-app-19de7.firebaseapp.com',
    storageBucket: 'note-app-19de7.firebasestorage.app',
  );
}
